### ISSUE TITLE
确实部分文件能不能提供，谢谢

### ISSUE THREAD

**Issue by timyliao** [laa-1/MachineTranslation#1]
能不能提供datasheet/train-zh，train-en相关的文件呢,谢谢

**Comment by laa-1** [comment]
我没有存档数据集的文件，它是 AI Challenger 的数据集，你可以在网上找一下有没有相关的资源，或者使用其他公开免费的数据集代替，比如WMT

**Comment by laa-1** [comment]
我没有存档数据集的文件，它是 AI Challenger 的数据集，你可以在网上找一下有没有相关的资源，或者使用其他公开免费的数据集代替，比如 WMT 数据集
